name: Build & Auto-Post

on:
  workflow_dispatch:  # ручной запуск через GitHub
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - main

on:
  schedule:
    - cron: '0 */6 * * *'  # каждые 6 часов
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}  # Hugging Face token

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests markdown jinja2 pillow

      - name: Generate AI post
        run: |
          python scripts/generate_ai_content.py

      - name: Build site
        run: |
          python scripts/build.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./_site
          # branch: gh-pages   # если хочешь деплой в отдельную ветку
